### PR TITLE
Fix: Drop Refinery29\Piston\ExceptionalPipeline in favour of League\Pipeline\Pipeline

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] drops `Refinery29\Piston\ExceptionalPipeline` in favour of `League\Pipeline\Pipeline`

Follows #164.

### CODE REVIEW

**Comment by localheinz** [comment]
@kayladnls @rcatlin 

As a result of this PR, there's actually no difference between `Refinery29\Piston\Middleware\ExceptionalPipeline` and `League\Pipeline\Pipeline` - can we remove it?

**Comment by kayladnls** [comment]
@localheinz can't honestly remember the reason why we needed to create an exceptional pipeline, but since they're the same now, remove away. Can we close this PR in favor of a PR that removes the file and updates references, then?

**Comment by localheinz** [comment]
@kayladnls 

Will do!

**Comment by localheinz** [comment]
@kayladnls 

Do you want to take a look again?

**Comment by kayladnls** [comment]
@localheinz looks good, just needs a rebase.

**Comment by localheinz** [comment]
@kayladnls 

Rebased!

**Comment by localheinz** [comment]
Thank you, @kayladnls!

**Pull request merged**
