### PR TITLE
Fix: Case

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] fixes the case of a directory

### CODE REVIEW

**Comment by rcatlin** [comment]
Tests fail:
```
Fatal error happened while executing the following 
    it pre processes a request with included resources 
    Class 'Refinery29\Piston\Stubs\StringEmitter' not found in /home/travis/build/refinery29/piston/spec/PistonSpec.php on line 58 
```

**Comment by localheinz** [comment]
@rcatlin 

Fixed!

**Comment by rcatlin** [comment]
Post Merge :+1:

**Comment by localheinz** [comment]
Thank you, @rcatlin!

**Pull request merged**
