### PR TITLE
Fix: Update codeclimate/php-test-reporter

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates `codeclimate/php-test-reporter`

💁‍♂️ For reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.2.0...v0.4.4.

### CODE REVIEW

**Comment by jhabdas** [comment]
Advise ditching CodeClimate. GitHub Marketplace has a Codecov integration and it will save you many pains I promise.

**Comment by jhabdas** [comment]
https://github.com/comfusion/hyperdrive/issues/56 - example PHP integration

**Comment by jhabdas** [comment]
I lied. The actual integration was a one-liner once set-up via GH market: https://github.com/comfusion/hyperdrive/commit/de48348f8f21ee9bcad11aabe7b9124614c184f9

**Comment by localheinz** [comment]
Thank you for the heads up, @jhabdas! Code Climate has been working fine for us, we'll see about using something different.

**Comment by jhabdas** [comment]
@localheinz in short, codecov was not only extremely easy to integrate, it supports build matricies, multiple coverage reports via tagging (e.g. `unittests`, `integration`), has prompt support and a dashboard which looks like this: https://codecov.io/gh/comfusion/hyperdrive

**Comment by localheinz** [comment]
Thank you, @ilanasufrin!

**Pull request merged**
