### PR TITLE
Enhancement: Provide MiddlewareInterface

### PR DESCRIPTION
**Pull request by localheinz**
#This PR

* [x] proposes a `MiddlewareInterface` to be used for future development

:information_desk_person: In order to easily allow `refinery29/piston` to use existing PSR-7 middleware, as well as to allow users of `refinery29/piston` to switch to a different framework, we should decide to use one of the available choices.

### Interface

A bunch of projects provide and/or use exactly the same interface, for example

* [`bitexpert/adroit`](https://github.com/bitExpert/adroit)
* [`madewithlove/glue`](https://github.com/madewithlove/glue)
* [`radar/adr`](https://github.com/radarphp/Radar.Adr)
* [`relay/relay`](https://github.com/relayphp/Relay.Relay/blob/1.x/src/MiddlewareInterface.php#L42)
* [`zendframework/zend-expressive`](https://github.com/zendframework/zend-expressive/blob/2db114f9c888e5ce06c808c44c47f70324be4d5c/src/Application.php#L138)
* [`zendframework/zend-stratigility`](https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewareInterface.php#L57)
* ...

### Existing Middleware using this interface

* [`akrabat/rka-ip-address-middleware`](https://github.com/akrabat/rka-ip-address-middleware)
* [`akrabat/rka-scheme-and-host-detection-middleware`](https://github.com/akrabat/rka-scheme-and-host-detection-middleware)
* [`bear/middleware`](https://github.com/bearsunday/BEAR.Middleware)
* [`hannesvdvreken/psr7-middlewares`](https://github.com/hannesvdvreken/psr7-middlewares)
* [`los/api-problem`](https://github.com/Lansoweb/api-problem)
* [`los/los-rate-limit`](https://github.com/Lansoweb/LosRateLimit)
* [`monii/monii-action-handler-psr7-middleware`](https://github.com/monii/monii-action-handler-psr7-middleware)
* [`monii/monii-nikic-fast-route-psr7-middleware`](https://github.com/monii/monii-nikic-fast-route-psr7-middleware)
* [`monii/monii-response-assertion-psr7-middleware`](https://github.com/monii/monii-response-assertion-psr7-middleware)
* [`mtymek/blast-base-url`](https://github.com/mtymek/blast-base-url)
* [`ocramius/psr7-session`](https://github.com/Ocramius/PSR7Session)
* [`oscarotero/psr7-middlewares`](https://github.com/oscarotero/psr7-middlewares)
* [`php-middleware/block-robots`](https://github.com/php-middleware/block-robots)
* [`php-middleware/http-authentication`](https://github.com/php-middleware/http-authentication)
* [`php-middleware/log-http-messages`](https://github.com/php-middleware/log-http-messages)
* [`php-middleware/maintenance`](https://github.com/php-middleware/maintenance)
* [`php-middleware/phpdebugbar`](https://github.com/php-middleware/phpdebugbar)
* [`php-middleware/request-id`](https://github.com/php-middleware/request-id)
* [`relay/middleware`](https://github.com/relayphp/Relay.Middleware)
* ...

For reference, see, for example: 

* https://akrabat.com/writing-psr-7-middleware/ 
* https://www.youtube.com/watch?v=MTzWlQo9sAk (https://speakerdeck.com/simensen/hello-psr-7-phpday-2015)
* http://weierophinney.github.io/2015-10-20-PSR-7-and-Middleware/#/
* https://www.youtube.com/watch?v=3AFR1BeiO2Q
* too many to list

### CODE REVIEW

**Comment by kayladnls** [comment]
I don't think this is beneficial in master. We have a 2.0 branch, we can put it there.

**Comment by rcatlin** [comment]
:+1:

**Comment by localheinz** [comment]
@kayladnls 

If we merged this into `master`, we could try a hybrid mode, where we allow to stack and process middleware implementing the

* `League\Pipeline\StageInterface`
* `Refinery29\Piston\Middleware\MiddlewareInterface`

What do you think?

/cc @rcatlin @settermjd

**Comment by kayladnls** [comment]
I think hybrid mode is a bad idea and would be messy and hard to understand. I think it's better to keep it a clean BC switch when we release a solid 2.0

**Comment by localheinz** [comment]
@kayladnls 

If we *add* the possibility to use middleware that implements `Refinery29\Piston\Middleware\MiddlewareInterface`, but not `League\Pipeline\StageInterface`, then that isn't a BC break, or would it?
If we *remove* the possibility to use `League\Pipeline\StageInterface`, then that would be a BC break, wouldn't it?

I agree, though, that it's not the cleanest solution.

**Pull request closed without merging**
